name: Test => Build => Deploy

on: push

jobs:
  python:
    name: Python tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev
      - name: Lint with mypy
        run: |
          find ${GITHUB_WORKSPACE}/src -name '*.py' ! -name '*_types.py' -exec pipenv run mypy {} +
      - name: Lint with flake8
        run: |
          pipenv run flake8 ${GITHUB_WORKSPACE}/src --count --show-source --statistics
      - name: Lint with pylint
        run: |
          find ${GITHUB_WORKSPACE}/src -name '*.py' | xargs pipenv run pylint --rcfile=.pylintrc
      - name: Test with pytest
        run: pipenv run pytest
