name: Test => Build => Deploy


on: push


jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry install -vv
      - run: make lint
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry install -vv
      - uses: pre-commit/action@v2.0.3
  test-python:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry install -vv
      - run: make test
