name: PR Target (opened)


on:
  pull_request_target:
    types:
      - opened
      - reopened


jobs:
  assign-author:
    name: Assign Author to PR
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1  # cspell:ignore technote
  label-pr:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.19.0
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
