name: On Push


on: push


defaults:
  run:
    shell: bash


env:
  NODE_VERSION: '20'


jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - uses: ITProKyle/action-setup-python@v0.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: make lint
  spellcheck:
    # There is an official action published by cSpell.
    # v1.1.1 was tested but did not function as desired so we are using the CLI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: make spellcheck
  test-python:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: ITProKyle/action-setup-python@v0.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: make test
