name: Pull Request Management

on: pull_request

jobs:
  labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: TimonVS/pr-labeler@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  wip:
    name: Set status
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
