name: Pull Request Management

on: pull_request

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: PR opened filter
        uses: actions/bin/filter@master
        args: action opened
      - name: PR Labeler
        uses: TimonVS/pr-labeler@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  wip:
    name: "Set status"
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@v1.0.0
