name: Pull Request Management

on: pull_request

jobs:
  label:
    name: Label Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Label based on branch prefix
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: TimonVS/pr-labeler@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
